# Generated by Django 5.1.1 on 2024-10-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_book_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
